apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-oom
  namespace: oom-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ktor-oom
  template:
    metadata:
      labels:
        app: ktor-oom
    spec:
      containers:
      - name: ktor-oom
        image: oldhorizon/ktor-oom:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 9100
        readinessProbe:
          httpGet:
            port: 8080
            path: /v1/ping
        volumeMounts:
        - mountPath: /dump
          name: dump-volume
      volumes:
      - name: dump-volume
        emptyDir: {}
