apiVersion: v1
kind: Service
metadata:
  name: ktor-oom-svc
  namespace: oom-sample
  annotations:
    prometheus.io/java_scrape: 'true'
    prometheus.io/java_port: '9100'
spec:
  selector:
    app: ktor-oom
  ports:
  - name: app
    protocol: TCP
    port: 8080
  - name: metrics
    protocol: TCP
    port: 9100
  type: NodePort
