apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: oom-sample
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'java'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_java_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_java_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
